export const classRemap = {
    "Tank": (spec) => specToClassMap[spec] || null,
    "Late": (spec) => specToClassMap[spec] || null,
    "Tentative": (spec) => specToClassMap[spec] || null,
    "Absence": (spec) => specToClassMap[spec] || null,
    "Bench": (spec) => specToClassMap[spec] || null,
    "Death Knight": "DK"
}

const specToClassMap = {
    "Blood_Tank": "DK",
    "Frost_DPS": "DK",
    "Unholy_DPS": "DK",
    "Death Knight": "DK",
    "Protection": "Warrior",
    "Arms": "Warrior",
    "Fury": "Warrior",
    "Guardian": "Druid",
    "Feral": "Druid",
    "Balance": "Druid",
    "Restoration": "Druid",
    "Protection1": "Paladin",
    "Retribution": "Paladin",
    "Holy1": "Paladin",
    "Assassination": "Rogue",
    "Combat": "Rogue",
    "Subtlety": "Rogue",
    "Survival": "Hunter",
    "Marksmanship": "Hunter",
    "Beast Mastery": "Hunter",
    "BM": "Hunter",
    "Fire": "Mage",
    "Arcane": "Mage",
    "Frost": "Mage",
    "Demonology": "Warlock",
    "Affliction": "Warlock",
    "Destruction": "Warlock",
    "Shadow": "Priest",
    "Discipline": "Priest",
    "Holy": "Priest",
    "Smite": "Priest",
    "Elemental": "Shaman",
    "Enhancement": "Shaman",
    "Restoration1": "Shaman"
};

export const roleMap = {
    "Blood_Tank": "Tank",
    "Frost_DPS": "Melee",
    "Unholy_DPS": "DK",
    "Death Knight": "DK",
    "Protection": "Warrior",
    "Arms": "Warrior",
    "Fury": "Warrior",
    "Guardian": "Druid",
    "Feral": "Druid",
    "Balance": "Druid",
    "Restoration": "Druid",
    "Protection1": "Paladin",
    "Retribution": "Paladin",
    "Holy1": "Paladin",
    "Assassination": "Rogue",
    "Combat": "Rogue",
    "Subtlety": "Rogue",
    "Survival": "Hunter",
    "Marksmanship": "Hunter",
    "Beast Mastery": "Hunter",
    "BM": "Hunter",
    "Fire": "Mage",
    "Arcane": "Mage",
    "Frost": "Mage",
    "Demonology": "Warlock",
    "Affliction": "Warlock",
    "Destruction": "Warlock",
    "Shadow": "Priest",
    "Discipline": "Priest",
    "Holy": "Priest",
    "Smite": "Priest",
    "Elemental": "Shaman",
    "Enhancement": "Shaman",
    "Restoration1": "Shaman"
}